import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import Navbar from "@/components/Navbar"
import { getSession } from "@/lib/session"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()
  return (
    <html lang="en">
      <body className="m-0">
        {/* page wrapper */}
        <div className="absolute flex min-h-screen w-full flex-col bg-gray-800">
          <Navbar session={session} />
          {/* content container */}
          <div className="relative top-[60px] w-full bg-gray-800">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
